name: Build

on:
  push:
    branches: [ main ]
    tags: ["**"]
  pull_request:
    branches: [ main ]

jobs:
  buildtestandpush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Version 
      id: vars
      run: |
        if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
          echo "version=latest" >> $GITHUB_ENV
        elif [[ $GITHUB_REF = refs/tags/* ]]; then
          echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
        else
          exit 1
        fi
        
    - name: Install requirements if any
      run: |
        docker --version
        python3 --version

    - name: build docker image
      run: |
        echo "version is ${version}"
        docker build -t equal-experts-gist-api:${version} .
        docker images | grep equal-experts-gist-api

    # - name: Vulnerability scan docker image
    #   run: |
    #     sudo apt-get install wget apt-transport-https gnupg lsb-release
    #     wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
    #     echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
    #     sudo apt-get update
    #     sudo apt-get install trivy

    #     trivy image --severity CRITICAL,HIGH equal-experts-gist-api:"${version}"


    - name: Unittest 
      run: |
        pip install -r requirements.txt
        python3 test_app.py
        coverage run --source=app -m unittest discover
        coverage report -m
        
     
        
