name: Build

on:
  push:
    branches: [ main ]
    tags: ["**"]
  pull_request:
    branches: [ main ]

jobs:
  buildtestandpush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Version 
      id: vars
      run: |
        if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
          echo "version=latest" >> $GITHUB_OUTPUT
        else [[ $GITHUB_REF = refs/tags/* ]]; then
          echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
        fi
        
    - name: Install requirements if any
      run: |
        docker --version
        python3 --version

    - name: build docker image
      run: |
        docker build -t equal-experts-gist-api:"${version}" .
        docker images | grep equal-experts-gist-api

    - name: Vulnerability scan docker image
      run: |
        sudo apt install wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.tar.gz
        tar -xzf trivy_0.49.1_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/
        trivy image --severity CRITICAL,HIGH equal-experts-gist-api:"${version}"
        
        
     
        
